apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: {{ .Values.namespace }}
  labels:
    app: traefik
    component: router
  annotations:
    # Use the legacy annotation (not the newer "external") which does not work in hyperpod
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    {{- if .Values.awsCertificateArn }}
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{ .Values.awsCertificateArn | quote }}
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    {{- end }}
    {{- if .Values.externalDns.enabled }}
    external-dns.alpha.kubernetes.io/hostname: "{{ .Values.domain }},*.{{ .Values.domain }}"
    {{- end }}
    # Configure NLB attributes according to AWS docs using the consolidated attributes approach
    # refer to https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_LoadBalancerAttribute.html
    # service.beta.kubernetes.io/aws-load-balancer-attributes: "load_balancing.cross_zone.enabled=true,access_logs.s3.enabled=false"
spec:
  type: LoadBalancer
  selector:
    app: traefik
    component: router
  ports:
  - port: 443
    name: websecure
    targetPort: web
    protocol: TCP