apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: {{ .Values.namespace }}
  labels:
    app: traefik
    component: router
spec:
  type: ClusterIP
  selector:
    app: traefik
    component: router
  ports:
  - port: 443
    name: websecure
    targetPort: web
    protocol: TCP