---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: jupyter-k8s-controller-manager
      namespace: system
      path: /mutate-workspace-jupyter-org-v1alpha1-workspace
      port: 9443
  failurePolicy: Fail
  name: mworkspace-v1alpha1.kb.io
  rules:
  - apiGroups:
    - workspace.jupyter.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - workspaces
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: jupyter-k8s-controller-manager
      namespace: system
      path: /validate-pods-exec-workspace
      port: 9443
  failurePolicy: Fail
  name: vpods-exec-workspace-v1.kb.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CONNECT
    resources:
    - pods/exec
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: jupyter-k8s-controller-manager
      namespace: system
      path: /validate-workspace-jupyter-org-v1alpha1-workspace
      port: 9443
  failurePolicy: Fail
  name: vworkspace-v1alpha1.kb.io
  rules:
  - apiGroups:
    - workspace.jupyter.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - workspaces
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: jupyter-k8s-controller-manager
      namespace: system
      path: /validate-workspace-jupyter-org-v1alpha1-workspacetemplate
      port: 9443
  failurePolicy: Ignore
  name: vworkspacetemplate-v1alpha1.kb.io
  rules:
  - apiGroups:
    - workspace.jupyter.org
    apiVersions:
    - v1alpha1
    operations:
    - UPDATE
    resources:
    - workspacetemplates
  sideEffects: None
