# This rule is not used by the project jk8s itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to servers.jupyter.org resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: jk8s
    app.kubernetes.io/managed-by: kustomize
  name: jupyterserver-viewer-role
rules:
- apiGroups:
  - servers.jupyter.org
  resources:
  - jupyterservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - servers.jupyter.org
  resources:
  - jupyterservers/status
  verbs:
  - get
