apiVersion: workspaces.jupyter.org/v1alpha1
kind: Workspace
metadata:
  labels:
    app.kubernetes.io/name: jupyter-k8s
    app.kubernetes.io/managed-by: kustomize
  name: workspace-stopped
spec:
  displayName: sample-stopped
  image: jupyter/minimal-notebook:latest
  desiredStatus: Stopped
  serviceAccountName: default
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"