apiVersion: workspace.jupyter.org/v1alpha1
kind: Workspace
metadata:
  labels:
    app.kubernetes.io/name: jupyter-k8s
    app.kubernetes.io/managed-by: kustomize
  name: workspace-with-template
spec:
  displayName: "Workspace Using Template"
  templateRef:
    name: "production-notebook-template"
    namespace: "jupyter-k8s-shared"
  desiredStatus: Running
  ownershipType: Public