{{- if .Values.authmiddleware.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: authmiddleware-secrets
  namespace: {{ .Values.namespace }}
  labels:
    app: authmiddleware
    component: auth
type: Opaque
data:
  # this value must be provided in .Values.authmiddleware.jwtSigningKey
  jwt-signing-key: {{ .Values.authmiddleware.jwtSigningKey | quote }}
{{- end }}