apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.connection.workspace.jupyter.org
  annotations:
    cert-manager.io/inject-ca-from: system/extension-server-cert
spec:
  service:
    name: extension-server
    namespace: system
  group: connection.workspace.jupyter.org
  version: v1alpha1
  groupPriorityMinimum: 100
  versionPriority: 100
  insecureSkipTLSVerify: false
  caBundle: ""  # Will be injected by cert-manager
