apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: extension-server-cert
  namespace: system
spec:
  secretName: extension-server-cert
  duration: 2160h  # 90 days
  renewBefore: 360h  # 15 days
  privateKey:
    rotationPolicy: Always
  subject:
    organizations:
      - jupyter-k8s-operator
  commonName: extension-server
  dnsNames:
    - extension-server.system.svc
    - extension-server.system.svc.cluster.local
  issuerRef:
    name: jupyter-k8s-selfsigned-issuer
    kind: Issuer
