apiVersion: v1
kind: Service
metadata:
  name: extension-server
  namespace: system
spec:
  selector:
    control-plane: controller-manager
  ports:
  - name: https
    port: 443
    targetPort: 7443
    protocol: TCP
  type: ClusterIP
